// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFF.Domain;

#nullable disable

namespace PFF.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consultations_Pathologies_JoinTable", b =>
                {
                    b.Property<int>("ConsultationsId")
                        .HasColumnType("int");

                    b.Property<int>("PathologiesId")
                        .HasColumnType("int");

                    b.HasKey("ConsultationsId", "PathologiesId");

                    b.HasIndex("PathologiesId");

                    b.ToTable("Consultations_Pathologies_JoinTable");
                });

            modelBuilder.Entity("Consultations_Travailleurs_JoinTable", b =>
                {
                    b.Property<int>("ConsultationsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkersSSIN")
                        .HasColumnType("int");

                    b.HasKey("ConsultationsId", "WorkersSSIN");

                    b.HasIndex("WorkersSSIN");

                    b.ToTable("Consultations_Travailleurs_JoinTable");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.ChronicTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Posologie");

                    b.Property<int>("PathologyId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PathologyId");

                    b.HasIndex("PatientId");

                    b.ToTable("TTChronique", null, t =>
                        {
                            t.HasCheckConstraint("CK_TTChronique_Posologie", "LEN(Posologie) > 0");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Évaluation");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Motif");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Objectif");

                    b.Property<int>("PathologyId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Plan");

                    b.Property<string>("Subjective")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Subjectif");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Consultation_Date", "Date <= GETDATE()");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HowToTake")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("MéthodePrise");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Médicament", null, t =>
                        {
                            t.HasCheckConstraint("CK_Médicament_MethodePrise", "LEN(TRIM(Nom)) > 0");

                            t.HasCheckConstraint("CK_Médicament_Nom", "LEN(TRIM(Nom)) > 0");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Pathology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pathologie", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pathologie_Nom", "LEN(TRIM(Nom)) > 0");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Surnom");

                    b.Property<string>("Allergies")
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Allergies");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateNaissance");

                    b.Property<string>("ConsumptionFrequency")
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("FréquenceConsommation");

                    b.Property<string>("DrugType")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("ProduitConsommé");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Prénom");

                    b.Property<string>("Gender")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Genre");

                    b.Property<bool?>("HasInsuranceCard")
                        .HasColumnType("BIT")
                        .HasColumnName("CarteMédicale");

                    b.Property<string>("IdNumber")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("NuméroID");

                    b.Property<int?>("Income")
                        .HasColumnType("INT")
                        .HasColumnName("Revenus");

                    b.Property<string>("Insurance")
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Mutuelle");

                    b.Property<DateTime?>("InsuranceCardEndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ExpirationCarteMédicale");

                    b.Property<DateTime?>("InsuranceEndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ExpirationMutuelle");

                    b.Property<bool?>("IsAtFedasil")
                        .HasColumnType("BIT")
                        .HasColumnName("Fedasil");

                    b.Property<bool?>("IsInsured")
                        .HasColumnType("BIT")
                        .HasColumnName("Assuré");

                    b.Property<bool?>("IsWorking")
                        .HasColumnType("BIT")
                        .HasColumnName("Travail");

                    b.Property<string>("LastName")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Nom");

                    b.Property<DateTime>("LastVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateDernièreVisite")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("PatientAddressId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("NuméroTéléphone");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateInscription")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SSIN")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("NISS");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Statut");

                    b.HasKey("Id");

                    b.HasIndex("PatientAddressId");

                    b.HasIndex("SSIN")
                        .IsUnique()
                        .HasFilter("[NISS] IS NOT NULL");

                    b.ToTable("Patient", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patient_DernièreVisite", "DateDernièreVisite >= DateInscription AND DateDernièreVisite <= GETDATE()");

                            t.HasCheckConstraint("CK_Patient_Identification", "LEN(TRIM(Prénom)) > 0 OR LEN(TRIM(Nom)) > 0 OR LEN(TRIM(Surnom)) > 0");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.PatientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Pays");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)")
                        .HasColumnName("Numéro");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Rue");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Ville");

                    b.Property<int>("ZipCode")
                        .HasColumnType("INT")
                        .HasColumnName("CodePostal");

                    b.HasKey("Id");

                    b.ToTable("AddressePatient", (string)null);
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateFin");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateDébut");

                    b.Property<string>("TakeFrequency")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("FréquencePrise");

                    b.Property<int>("WorkerSSIN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("WorkerSSIN");

                    b.ToTable("Prescription", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prescription_Dates", "DateDébut < DateFin");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.VitalSign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BMI")
                        .HasColumnType("FLOAT")
                        .HasColumnName("IMC");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("PressionArtérielle");

                    b.Property<double>("BloodSugar")
                        .HasColumnType("FLOAT")
                        .HasColumnName("Glycémie");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("INT")
                        .HasColumnName("FréquenceCardiaque");

                    b.Property<double>("Height")
                        .HasColumnType("FLOAT")
                        .HasColumnName("Taille");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("INT")
                        .HasColumnName("Saturation");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("DECIMAL(3, 1)")
                        .HasColumnName("Température");

                    b.Property<int>("Weight")
                        .HasColumnType("INT")
                        .HasColumnName("Poids");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ParamètresVitaux", null, t =>
                        {
                            t.HasCheckConstraint("CK_Paramètres_FréquenceCardiaque", "FréquenceCardiaque <= 220");

                            t.HasCheckConstraint("CK_Paramètres_Saturation", "Saturation >= 1 AND Saturation <= 100");

                            t.HasCheckConstraint("CK_Paramètres_Température", "Température >= 30 AND Température <= 45");
                        });
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Worker", b =>
                {
                    b.Property<int>("SSIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSIN"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateNaissance");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Pays");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Prénom");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("Genre");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Nom");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)")
                        .HasColumnName("Numéro");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Fonction");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("NuméroTéléphone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Rue");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Ville");

                    b.Property<int>("ZipCode")
                        .HasColumnType("INT")
                        .HasColumnName("CodePostal");

                    b.HasKey("SSIN");

                    b.ToTable("Travailleur", null, t =>
                        {
                            t.HasCheckConstraint("CK_Travailleur_Email", "Email LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Travailleur_Noms", "LEN(TRIM(Prénom)) > 0 AND LEN(TRIM(Nom)) > 0");
                        });
                });

            modelBuilder.Entity("Prescriptions_Médicaments_JoinTable", b =>
                {
                    b.Property<int>("MedicinesId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionsId")
                        .HasColumnType("int");

                    b.HasKey("MedicinesId", "PrescriptionsId");

                    b.HasIndex("PrescriptionsId");

                    b.ToTable("Prescriptions_Médicaments_JoinTable");
                });

            modelBuilder.Entity("TTChronique_Médicaments_JoinTable", b =>
                {
                    b.Property<int>("ChronicTreatmentsId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinesId")
                        .HasColumnType("int");

                    b.HasKey("ChronicTreatmentsId", "MedicinesId");

                    b.HasIndex("MedicinesId");

                    b.ToTable("TTChronique_Médicaments_JoinTable");
                });

            modelBuilder.Entity("Consultations_Pathologies_JoinTable", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Consultation", null)
                        .WithMany()
                        .HasForeignKey("ConsultationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Pathology", null)
                        .WithMany()
                        .HasForeignKey("PathologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consultations_Travailleurs_JoinTable", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Consultation", null)
                        .WithMany()
                        .HasForeignKey("ConsultationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersSSIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.ChronicTreatment", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Pathology", "Pathology")
                        .WithMany("ChronicTreatments")
                        .HasForeignKey("PathologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Patient", "Patient")
                        .WithMany("ChronicTreatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathology");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Consultation", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Patient", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.PatientAddress", "PatientAddress")
                        .WithMany("Patients")
                        .HasForeignKey("PatientAddressId");

                    b.Navigation("PatientAddress");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Prescription", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Consultation", "Consultation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Worker", "Worker")
                        .WithMany("Prescriptions")
                        .HasForeignKey("WorkerSSIN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Patient");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.VitalSign", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Consultation", "Consultation")
                        .WithMany("VitalSigns")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Prescriptions_Médicaments_JoinTable", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTChronique_Médicaments_JoinTable", b =>
                {
                    b.HasOne("PFF.Domain.Model.Entities.ChronicTreatment", null)
                        .WithMany()
                        .HasForeignKey("ChronicTreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFF.Domain.Model.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Consultation", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Pathology", b =>
                {
                    b.Navigation("ChronicTreatments");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Patient", b =>
                {
                    b.Navigation("ChronicTreatments");

                    b.Navigation("Consultations");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.PatientAddress", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PFF.Domain.Model.Entities.Worker", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
